[package]
name = "openprinttag-core"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = ["std"]
all = ["std"]

std = ["thiserror/std"]

[dependencies.uuid]
version = "1.18"
features = ["v5"]

[dependencies.chrono]
version = "0.4"

[dependencies.minicbor]
version = "2.1"
default-features = false

[dependencies.thiserror]
version = "2.0"
default-features = false

[build-dependencies]
openprinttag-codegen = { path = "../openprinttag-codegen" }
