[package]
name = "openprinttag-codegen"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
all = ["url-loader", "format"]
default = ["url-loader", "format"]

tracing = ["dep:tracing"]

url-loader = ["dep:ureq"]
format = ["dep:prettyplease"]

[dependencies.thiserror]
version = "2.0"

[dependencies.tracing]
version = "0.1"
features = ["std", "attributes", "log", "tracing-attributes"]
default-features = false
optional = true

[dependencies.syn]
version = "2.0"
features = ["full"]

[dependencies.proc-macro2]
version = "1.0"

[dependencies.quote2]
version = "0.9"

[dependencies.prettyplease]
version = "0.2"
optional = true

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_norway]
version = "0.9"

[dependencies.derive-new]
version = "0.7"

[dependencies.strum]
version = "0.27"
features = ["derive"]

[dependencies.ureq]
version = "3.1"
features = ["gzip", "rustls"]
default-features = false
optional = true

[dependencies.parking_lot]
version = "0.12"
